### ISSUE TITLE
Get the current status of a package

### ISSUE THREAD

**Issue by ITSYV** [DivideBV/Postnl#1]
How can you get the current status of the transport?
Every time I trie to use the "currentStatus" function or the "currentStatusByReference" function I get this error:
"The user is not authorized for the method 'CurrentStatus'."

**Comment by ameenross** [comment]
If you have authorization issues, you probably need to consult with the CIT service desk first. They explicitly have to enable the status service for the account.

**Comment by ITSYV** [comment]
Ok thanks!
