### ISSUE TITLE
Set Receiver Email and Phonenumber

### ISSUE THREAD

**Issue by PaulVanDeKamer** [DivideBV/Postnl#16]
Hi,

How can we set the Receiver email and Phonenumber trhough this api?

**Comment by slokhorst** [comment]
Extending the example, before the `$client->generateLabel($shipment)` line:

``` php
$contact = new ComplexTypes\Contact('01', $Email, $SMSNr, $TelNr);
$contacts = new ComplexTypes\ArrayOfContact([$contact]);
$shipment->setContacts($contacts);
```

**Comment by PaulVanDeKamer** [comment]
Hi, thanks for your update. This is generating an error:

PHP Fatal error:  Call to undefined function DivideBV\Postnl\ComplexTypes\Contact() in 
postnl.php on line 92

**Comment by slokhorst** [comment]
Oops, sorry about that, I've updated the example.

**Comment by PaulVanDeKamer** [comment]
HI again. This seems to be working. Thank you!
