### ISSUE TITLE
Increased responsibility

### ISSUE THREAD

**Issue by PaulVanDeKamer** [DivideBV/Postnl#18]
When creating a label with code (3087) the system is not creating a label. Proberly because there must be a value be send over with the ammount of increased responsibility. 
Is this possible through the API?

**Comment by ameenross** [comment]
What response do you get? I expect CIF to return an exception, which you should be able to catch.

**Comment by PaulVanDeKamer** [comment]
Thats the strange thing. When creating a label with ProductCodeDelivery 3087 nothing will return.

**Comment by ameenross** [comment]
May I see your code to reproduce the problem?

**Comment by PaulVanDeKamer** [comment]
This code is working for productcodes: 
3085 (Standard Shipment) 
3089 (Signature Needer) 
3385 (Houseadres Only)  etc... but not for ProductCodeDelivery 3087 (Increased responsibility)

$client = new Postnl(
    xxxxxxx,   // Customer number
    'ccccc',     // Customer code
    'name',  // Customer name
    'username',     // Username
    'password', // Password
    collection,     // Collection location
    'globalpack',   // Globalpack
    false        // Whether to use PostNL's sandbox environment.
);

/**
- Jan Smit
- Smit & Zonen
- Hoofdstraat 1A
- 1234 AB Heikant
- The Netherlands
  */
  $receiverAddress = ComplexTypes\Address::create()
  ->setAddressType('01')
  ->setFirstName("$AflInitials")
  ->setName("$AflSurName")
  ->setCompanyName("$AflCompanyName")
  ->setStreet("$AflAddress")
  ->setHouseNr("$AflHouseNumber")
  ->setHouseNrExt('')
  ->setZipcode("$AflZipCode")
  ->setCity("$AflCity")
  ->setCountrycode("$AflCountry")
  ;

$senderAddress = ComplexTypes\Address::create()
    ->setAddressType('02')
    ->setFirstName('')
    ->setName('')
    ->setCompanyName('Company Name')
    ->setStreet('Company Street')
    ->setHouseNr('Company House')
    ->setHouseNrExt('')
    ->setZipcode('Company Zip')
    ->setCity('Company City')
    ->setCountrycode('NL');

// Request a barcode from PostNL.
$barcode = $client->generateBarcodeByDestination($receiverAddress->getCountryCode());
// Create a shipment.
$shipment = ComplexTypes\Shipment::create()
    ->setAddresses(new ComplexTypes\ArrayOfAddress([
        $receiverAddress,
        $senderAddress,
    ]))
    ->setRemark("$ordernummer")
    ->setBarcode($barcode)
    ->setDimension(ComplexTypes\Dimension::create()
        ->setWeight($gewicht) // Weight in g
    )
    ->setProductCodeDelivery("3087");         <----- ProductCodeDelivery  3087 Increased responsibility

$group = ComplexTypes\Group::create()
    ->setGroupSequence(1)
    ->setGroupCount(2)
    ->setGroupType('03')
    ->setMainBarcode($barcode);
$shipment->setGroups(new ComplexTypes\ArrayOfGroup([$group]));

// Generate label and confirm shipment.

$contact = new ComplexTypes\Contact('01', $AflEmail, $SMSNr, $AflTelefoon);
$contacts = new ComplexTypes\ArrayOfContact([$contact]);
$shipment->setContacts($contacts);

$result = $client->generateLabel($shipment, 'GraphicFile|PDF' );

**Comment by ameenross** [comment]
So you should wrap the `generateLabel()` call in a try catch block, then you'll see what error CIF returns.

**Comment by PaulVanDeKamer** [comment]
The warning/error thrown is:

 [Description:protected] => Validation failed for shipment: 3STXTQ794490743, Messages: Parent shipment does not contain Insurance amount,Insurance value is invalid
[ErrorNumber:protected] => 1003

So a valid Insurance Value must be submitted in someway... Could you please advice how i can do this?

**Comment by ameenross** [comment]
You need to tell CIF what the monetary value of the shipment is. To do that, you should add an `ArrayOfAmount` to the `Shipment`. Something like this:

``` php
// Create the insurance amount.
$amount = ComplexTypes\Amount::create()
    ->setAmountType('02')
    ->setValue('500.00');

// Add the amount to the shipment.
$shipment->setAmounts(new ComplexTypes\ArrayOfAmount([$amount]));
```

**Comment by digipact** [comment]
Through some trial and error I've found out that the "_Parent shipment does not contain Insurance amount,Insurance value is invalid_" error occurs when you're performing a label request where your `GroupSequence` is greater than 1. (Did you invert the values for `GroupCount` and `GroupSequence` by any chance? Right now it says that there's 1 package and you're processing package 2.)

When dealing with multi-collo shipments only the main package can contain an `Amount` definition. So you will need to reset the `ArrayOfAmount` to null for for any package with a sequence greater than 1.
