### ISSUE TITLE
Namespaces are not working properly. Getting error "Fatal error: Class 'Postnl' not found"

### ISSUE THREAD

**Issue by vkas002** [DivideBV/Postnl#2]
Hi , 

I am trying to integrate the POSTNL api on local server whose php version is 5.5.15 and namespaces are also active in php.ini. I have created a index.php (inside  /DivideBV/Postnl/ ) and  has same code which you have mention in the example . But when i trying to run the index.php it give fatal error : "Fatal error: Class 'Postnl' not found".

Can you please help me regarding this . 
Thank you

**Comment by ameenross** [comment]
http://php.net/manual/en/language.namespaces.basics.php

**Comment by ameenross** [comment]
I added use clauses to the example code as clarification.
