### ISSUE TITLE
Can we use this fo bulk shipments/labels etc?

### ISSUE THREAD

**Issue by mfprogrammer** [DivideBV/Postnl#3]
Hi, Can we create labels in bulk?

**Comment by ameenross** [comment]
I have tried confirming shipments in bulk (multiple `Shipment` in an `ArrayOfShipment`) but ran into problems. Then I was told by PostNL that it wasn't possible to do in bulk. So basically you have to wrap your single shipment in an `ArrayOfShipment`, just for fun :smile:

**Comment by mfprogrammer** [comment]
Haha..yea. Thats not very smart of PostNL :)
Another thing that I was wondering was how do we add 4 labels in one PDF. Looking at their documentation you can set the position of the content on the PDF, but I'm not able to figure out how to have 4 labels in on pdf.
Would be great if you could help me with that!

Thanks.

**Comment by ameenross** [comment]
For multicollo shipments, I presume? I had the same problem. I ended up requesting the PDFs one by one and then merging them using ghostscript. Your hosting needs to have the `gs` executable available and runnable from PHP, though.

``` php
$input = '';
foreach ($filenames as $filename) {
    $input .= ' ' . escapeshellarg($filename);
}
exec("gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile={$destination} {$input}");
```

**Comment by mfprogrammer** [comment]
This is really bad man..they are contradicting their own documentation here. Hard to believe they do not have a solution for this.
But anyways thanks for the script.

**Comment by ameenross** [comment]
You're referring to the grouping functionality in the documentation? That basically only tells PostNL that 2 separate labels are 1 shipment. It doesn't give a combined PDF unfortunately...

CIF is a low-level API so it does feel rather clunky.

**Comment by mfprogrammer** [comment]
Ohh..So yo mean: if one guy ordered 3 products , then we will have 3 labels on the same PDF ie. one shipment?

**Comment by ameenross** [comment]
Yeah, if those 3 products are packed separately in 3 boxes. Each box requires a label.

**Comment by mfprogrammer** [comment]
ok, but what if one user has 3 different products and i want to send them in one package?

**Comment by ameenross** [comment]
That's irrelevant unless you want/need to tell PostNL what's in the box. But then obviously you only need to request 1 label.

**Comment by mfprogrammer** [comment]
ok. Makes sense.

**Comment by slokhorst** [comment]
I also have a question about multi-collo shipments. The manual says the following:

> For shipments within the Netherlands, multi collo shipments can be created. Using CIF, this can be
> done as follows:
> - create a separate request per parcel to retrieve a label or to confirm the shipment (or both at
>   once)
> - connect the parcels by using the Group type in each request. Mention the amount of parcels in
>   the shipment (GroupCount), the number of the specific Parcel (GroupSequence) and the
>   main barcode of the shipment (MainBarcode) and specify Multicollo as the GroupType
>   (GroupType 03)

The first step is easy: run `Postnl::generateLabel()` multiple times.
But I'm not sure how to do the second step using this library. The `Postnl::confirming()` function doesn't allow me to "mention the main barcode of the shipment" and "specify Multicollo as the GroupType".

How should I do this? Thanks!

**Comment by ameenross** [comment]
Here's an example of how to do it (after creating the shipment complextype).

``` php
// Add group for multi-collo shipments.
if ($total > 1) {
    $group = ComplexTypes\Group::create()
        ->setGroupSequence($index)
        ->setGroupCount($total)
        ->setGroupType('03')
        ->setMainBarcode($mainBarcode);
     $postnlShipment->setGroups(new ComplexTypes\ArrayOfGroup([$group]));
}
```

**Comment by slokhorst** [comment]
@ameenross Great, thanks!

**Comment by slokhorst** [comment]
I created a small [example wiki page](../wiki/Multi-collo-shipment). Hopefully it will be useful to someone.

**Comment by ameenross** [comment]
Thanks for the contribution :)

**Comment by mfprogrammer** [comment]
@slokhorst  thanks for the wiki page https://github.com/DivideBV/Postnl/wiki/Multi-collo-shipment
I tried using it but I have a small issue saving it.
How do you save the multiple results in one pdf?

`foreach ($result1->getLabels() as $label) {
            $i++;
            $file_n = $_SERVER['DOCUMENT_ROOT'].'/controller/Export_History/EXPORT_DATA/LABELS/' . date('Y') . '/' . date('m') . '/' . date('d') . '/' . $file_name . '.pdf';
            //$file = new \SplFileObject($file_n, 'w',true);
            //echo $label->getContent(); exit;
            $handle = fopen($file_n, "w");
            echo fwrite($handle, $label->getContent());
            fclose($handle);
        }`

this is how my code looks to save the pdf.

**Comment by ameenross** [comment]
PostNL does not have a way to combine the labels in a single PDF. You need to process the PDFs yourself to achieve this result.

One way to combine the labels in a single PDF is to use the `gs` runtime. It does add an external requirement however. Example (`$filenames` is an array of the filename of each saved PDF):

``` php
$destination = escapeshellarg('postnl/shippinglabel_123.pdf');
$input = '';
foreach ($filenames as $filename) {
    $input .= ' ' . escapeshellarg($filename);
}

exec("gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile={$destination} {$input}");
```

**Comment by mfprogrammer** [comment]
@ameenross  - I get the 'gs' thing you say. It will allow me to make a single pdf by combining all the pdfs.

But what I actually need to know is how to store 4 labels in _one_ page in a single pdf file.
I have attached an example.
![pdf](https://cloud.githubusercontent.com/assets/15145978/14881474/c6ea2484-0d51-11e6-8ce9-c68be4ce7de6.png)

**Comment by ameenross** [comment]
You'd have to do things with [Imagemagick](http://php.net/manual/en/class.imagick.php).

**Comment by slokhorst** [comment]
See [this question](http://stackoverflow.com/questions/9034545/php-and-ghostscript-to-convert-a-multipage-pdf-to-a-single-jpg) to get started.

**Comment by ameenross** [comment]
@mfprogrammer It should be possible to do in PHP, though help with that is rather far beyond the scope of supporting this library.

You might be better off with a proper label printer of the right size though.

**Comment by mfprogrammer** [comment]
@ameenross Thanks for the suggestion. Do you know about any label printer that would do this job right?

**Comment by slokhorst** [comment]
@mfprogrammer PostNL has a [list of certified label printers](http://www.postnl.nl/klantenservice/veelgestelde-vragen/versturen/parcelware/met-welke-printers-werkt-parcelware.html), but any printer that can print A6 labels should work.
