### ISSUE TITLE
Set the Labeltype

### ISSUE THREAD

**Issue by Hill103** [DivideBV/Postnl#37]
Hi, how can the labeltype be set (normal package or brievenbuspakje etc)?

Thanks in advance.

**Comment by slokhorst** [comment]
Are you using the right ProductCode? I believe you need `2928` for brievenbuspakje ([see this](https://developer.postnl.nl/apis/barcode-webservice/how-use), ask PostNL to be sure). You can't manually set labeltype.

**Comment by Hill103** [comment]
Thanks! I probably skipped the part in the documentation where they state the labeltype is in the response, not a setting.
