### ISSUE TITLE
Set Evening delivery

### ISSUE THREAD

**Issue by stuiterbal1984** [DivideBV/Postnl#39]
Hi,

How can we set the Evening delivery trhough this api?

**Comment by ameenross** [comment]
You need to refer to the PostNL documentation. They maintain lists of product codes you need to use. See: https://developer.postnl.nl/apis/confirming-webservice/how-use and search for "evening delivery".

**Comment by stuiterbal1984** [comment]
Thanks for your quick response,


i See there the productcode: 3385 Deliver to stated address
But for a Standard shipment only stated address have the same productcode.

On the documentation stay: It is mandatory to use a combination of product code and a product option. The PostNL frontend will return this product option.
Combine these product codes with the following product option:
- product option: characteristic 118, option 006
- Delivery date is required:
Evening delivery must be allowed on the given delivery date
- Evening delivery must be allowed on the address specified
Receiver contact mobile or email is required

Sow, how i do this?

**Comment by ameenross** [comment]
Use `setProductOptions` on the shipment.

```php
$shipment->setProductOptions(new ComplexTypes\ArrayOfProductOption([
    new ComplexTypes\ProductOption(118, "007"),
]));
```
