### ISSUE TITLE
Requires soap PHP extension

### ISSUE THREAD

**Issue by slokhorst** [DivideBV/Postnl#4]
This package requires the `soap` PHP extension, but that wasn't immediately clear to me. Could you mention this in the readme (in the installation section maybe)?

Besides that, THANK YOU for this awesome package. I can't imagine how much work this has saved me. You rock!

**Comment by ameenross** [comment]
You're quite welcome. I added the SOAP requirement to both the composer.json and the readme. Also upped the version to 0.5.0
