### ISSUE TITLE
What printerType are available, need png

### ISSUE THREAD

**Issue by timo002** [DivideBV/Postnl#45]
Hello,

I've used the 0.6.0 version of the repository. Now I want to update and all seems to be working fine, except that I'm getting a PDF returned instead of a PNG. Now I figured out that it is possible to change the `printerType`, which is default `PDF`. But how to get a PNG?

I don't want a PDF, I need a PNG. The PNG is directly send to a Dymo printer, I'm not storing the labels.

**Comment by timo002** [comment]
After some debugging version 0.6.0, I found out that the default at moment was `'GraphicFile|PNG 300 dpi'`. Using this value as `printerType` returns a PNG. I tested with `PNG`, but not with the dpi.

It would be useful to add a list of possible `printerTypes`.

**Comment by ameenross** [comment]
As noted before (probably useful to add to the README), you still need PostNL's documentation. The list you want is there (and up-to-date).
