### ISSUE TITLE
getSentDate not part of postnl class

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [DivideBV/Postnl#49]
Why is getSentDate not part of postnl class? getDeliveryDate is available.

**Comment by ameenross** [comment]
Shouldn't it be `getSentDate()`? Send with a 'd' is actually a language error here.

**Comment by matthijs-neijenhuijs** [comment]
Yes it is Sent, sorry. In the title it was correct. But the question still remains?

**Comment by slokhorst** [comment]
The function is already implemented in the [`DeliveryDateClient`](https://github.com/DivideBV/Postnl/blob/master/src/DeliveryDateClient.php#L51) class, but not in the main `Postnl` class. I don't know why.

You can still use it though, like so:
```php
$request = new ComplexTypes\GetSentDateRequest(...);
$postnl->call('DeliveryDateClient', 'getSentDate', $request);
```

**Comment by ameenross** [comment]
The idea was to not implement a proxy function for each and every method of every client, only those that are regularly used. That's why I allowed for calling the client and method specifically.

**Comment by matthijs-neijenhuijs** [comment]
I think getSentDate is regularly used. You need this date, because its essential for sending a package. If you sent it on a different day, they cannot comply to your delivery date.

**Comment by ameenross** [comment]
Alright, pull request adding the function is welcomed.
