### ISSUE TITLE
Using an multi-colli

### ISSUE THREAD

**Issue by qualityplatforms** [DivideBV/Postnl#56]
Hello there,

Has this class the possibility to request an multi-colli? And if this is possible, can someone give me an example how to use this?

Thanks in advance.
Best regards,
Mark.

**Comment by slokhorst** [comment]
Yup, see [wiki/Multi-collo-shipment](https://github.com/DivideBV/Postnl/wiki/Multi-collo-shipment).

**Comment by qualityplatforms** [comment]
Why won't this work? 
`$result = $client->generateLabels(new ComplexTypes\ArrayOfShipment([$shipment1,$shipment2]));
$result->getLabels()[0];`

I get the following error:

>  Fatal error: Call to undefined method DivideBV\Postnl\ComplexTypes\GenerateLabelResponse::getLabels()

**Comment by slokhorst** [comment]
See #44
