### ISSUE TITLE
generate pick-up label

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [DivideBV/Postnl#57]
For generating a pick-up label we need to set a address for the customer. See: 

https://developer.postnl.nl/apis//pickup-postnl-location-shipment-labelling-example

It is not possible to setAddress for client.

**Comment by ameenross** [comment]
You don't set the address on the client. You create an object of the correct type and pass it to the function. You should be able to adapt the example in the readme to return a pickup label.
