### ISSUE TITLE
Unsupported Globalpack barcode type

### ISSUE THREAD

**Issue by JeroenBakker** [DivideBV/Postnl#6]
Our account manager at PostNL gave us a Globalpack key that starts with CV, but in dividebv/postnl/src/Postnl.php on line 181 there is no support for this type.

By adding support for this type myself I can see that their API definitely accepts the type (whereas a made up type of CQ is not allowed), so it's unlikely to be a typo by our account manager.

**Comment by slokhorst** [comment]
Maybe they changed this recently?
In the Barcode specification version 1_1, dated August 14, 2015, it states that only `CC`,`CD`,`CF` and `CP` are used for GlobalPack. I'm not sure if that is the latest revision.

**Comment by JeroenBakker** [comment]
I guess it's possible, we received this information around December 17, 2015.

Do you have a URL where I could read the specification myself? I'm finding it very hard to find anything specific on the GlobalPack barcode specification.

**Comment by slokhorst** [comment]
I don't have an URL.. I got it per email from PostNL when applying for access to the API, you should have too. I'm not sure if I'm allowed to share it.

By the way, I just noticed I was also given a `CV` Global Pack key! They probably forgot to update their documentation.

**Comment by JeroenBakker** [comment]
Will you add the CV type, or should I create a pull request?

**Comment by ameenross** [comment]
Yeah, PostNL's documentation is... not my favorite, I'll leave it at that.

They used to have it online somewhere, now you have to ask them to receive it in your email inbox. I don't know of a way to stay updated on the latest changes, never mind the undocumented stuff I've run into.

If you can quote a recent version of the docs, that'll do. I'll see if I can get a newer version of the docs in the meantime.

In the light of PostNL adding new barcodes all the time, it might be a good idea to just remove the sanity check.

**Comment by ameenross** [comment]
So as the `CV` barcode type was added, tentatively closing this issue.
