### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by qualityplatforms** [DivideBV/Postnl#60]
Hello there,

Since we have a problem with implentation of a new product of PostNL we have problems with the implentation. PostNL ask us about the request URL and all logs of the request, but i can't give it to them because the API has no debugging features. 

Can someone help me by adding those features?

Thanks in advance.

**Comment by ameenross** [comment]
That already exists. The main Postnl class has a `debug()` method.

https://github.com/DivideBV/Postnl/blob/master/src/Postnl.php#L524
