### ISSUE TITLE
PostNL API (CIF) new platform (live in november 2018)

### ISSUE THREAD

**Issue by Soetens** [DivideBV/Postnl#61]
PostNL announced that the old CIF platform users will be migrated to the new platform.

Endpoint will change and username/password combo's will be replaced by an API key.

How does this effect this lib?

**Comment by slokhorst** [comment]
#58 should fix this.

**Comment by PaulVanDeKamer** [comment]
Any Updates on this topic?

**Comment by ameenross** [comment]
#58 has been merged, and 2.0.0-beta1 released. I wasn't confident enough to release it as stable. But you should be able to install and test it.
