### ISSUE TITLE
CN23 forms for Customs

### ISSUE THREAD

**Issue by Soetens** [DivideBV/Postnl#73]
I can see in
DivideBV\Postnl\ComplexTypes\Label the method setLabeltype.
I would like to assume this can be used for the CN23 form (A5) labeltype.

But I cant see where it wil get it's use or how to put it in use.

**Comment by ameenross** [comment]
A label is returned by PostNL when you call the generateLabel endpoint. You need to use the correct product code. See: https://developer.postnl.nl/browse-apis/send-and-track/labelling-webservice/documentation/
