### ISSUE TITLE
Error Code 13308 "Due to the COVID-19 pandemic we currently cannot ship to this destination"

### ISSUE THREAD

**Issue by Soetens** [DivideBV/Postnl#77]
Error code 13308 seems to be undocumented by PostNL, but this means
`Due to the COVID-19 pandemic we currently cannot ship to this destination`

So PostNL does not ship to certain locations anymore, in this case Belgium.

Stay Safe everyone!

**Comment by ameenross** [comment]
I guess this is no longer relevant.
