### ISSUE TITLE
Update of PostNL API 2020

### ISSUE THREAD

**Issue by MAKE-Robbert** [DivideBV/Postnl#78]
Given the fact that PostNL will be updating their API in such a way;

The shipping API combines the functionalities of the following webservices:
- Labelling, 
- Confirming,
- Barcode 
- Easy Return - this is a new service that does not have any other documentation yet (I cannot find it). The Easy Return service will allow consumers abroad to easily return purchased goods.

------

Will this repository be updated to be able to connect to that API?

**Comment by ameenross** [comment]
Don't count on it. I don't have enough free time to work on this project currently and it's not sponsored by my current employer.

**Comment by MAKE-Robbert** [comment]
I see - I understand your constraints.
Do you by chance know about a repo that does a very similar job?

**Comment by BBrunekreeft** [comment]
Have a look at https://github.com/firstred/postnl-api-php

**Comment by ameenross** [comment]
https://github.com/firstred/postnl-api-php/issues/74
