### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by michieljakobs** [DivideBV/Postnl#81]
Currently only PHP version 5.6 to 7 is supported.
When is PHP 8 expected to be supported?

![php8-support](https://user-images.githubusercontent.com/3677681/132505198-b54e12b6-af0c-4d87-8bb2-12351c8eef52.png)

**Comment by michieljakobs** [comment]
After running "composer update", I still get an error message. This message is similar to the first.

![afbeelding](https://user-images.githubusercontent.com/3677681/132505908-59df8066-8535-4acf-a008-787729da8a34.png)

**Comment by ameenross** [comment]
I don't think there's any reason that it's not compatible with PHP 8. And in fact I think PHP nowadays is stable enough to just have open-ended PHP support (`>=7.1.0` for example)

**Comment by ameenross** [comment]
I tagged a new release... report back if it turns out compatibility *is* an issue.
